# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messaging.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\"U\n\x06Header\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x10\n\x08\x64\x61ta_len\x18\x02 \x01(\r\x12\r\n\x05srcid\x18\x03 \x01(\r\x12\r\n\x05\x64stid\x18\x04 \x01(\r\x12\r\n\x05msgid\x18\x05 \x01(\r\"J\n\nAckMessage\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x13\n\x0breturn_code\x18\x02 \x01(\r\x12\x0e\n\x06msg_id\x18\x03 \x01(\r\"6\n\x0cStateMessage\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\r\n\x05state\x18\x02 \x01(\r\"8\n\x0fResponseMessage\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\";\n\x0b\x44\x65liveryAck\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x13\n\x0breturn_code\x18\x02 \x01(\r\"\x17\n\tIPMessage\x12\n\n\x02ip\x18\x01 \x01(\r\"\x1d\n\x0bNodeMessage\x12\x0e\n\x06nodeid\x18\x01 \x01(\r\"4\n\x0bSendMessage\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"N\n\x0eReceiveMessage\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x13\n\x0breturn_code\x18\x02 \x01(\r\x12\x0e\n\x06msg_id\x18\x03 \x01(\r\"5\n\x0cMessageReply\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\\\n\rHeaderMessage\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x61ta_len\x18\x02 \x01(\x05\x12\r\n\x05srcid\x18\x03 \x01(\x05\x12\r\n\x05\x64stid\x18\x04 \x01(\x05\x12\r\n\x05msgid\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADER']._serialized_start=19
  _globals['_HEADER']._serialized_end=104
  _globals['_ACKMESSAGE']._serialized_start=106
  _globals['_ACKMESSAGE']._serialized_end=180
  _globals['_STATEMESSAGE']._serialized_start=182
  _globals['_STATEMESSAGE']._serialized_end=236
  _globals['_RESPONSEMESSAGE']._serialized_start=238
  _globals['_RESPONSEMESSAGE']._serialized_end=294
  _globals['_DELIVERYACK']._serialized_start=296
  _globals['_DELIVERYACK']._serialized_end=355
  _globals['_IPMESSAGE']._serialized_start=357
  _globals['_IPMESSAGE']._serialized_end=380
  _globals['_NODEMESSAGE']._serialized_start=382
  _globals['_NODEMESSAGE']._serialized_end=411
  _globals['_SENDMESSAGE']._serialized_start=413
  _globals['_SENDMESSAGE']._serialized_end=465
  _globals['_RECEIVEMESSAGE']._serialized_start=467
  _globals['_RECEIVEMESSAGE']._serialized_end=545
  _globals['_MESSAGEREPLY']._serialized_start=547
  _globals['_MESSAGEREPLY']._serialized_end=600
  _globals['_HEADERMESSAGE']._serialized_start=602
  _globals['_HEADERMESSAGE']._serialized_end=694
# @@protoc_insertion_point(module_scope)
