from nsb_client import NSBApplicationClient
...

class AppObject:
    # Initialization.
    def __init__(self, ...):
        ...
        self.conn = NSBApplicationClient()
        ...
    # Sending and receiving.
    def some_method(self, ...):
        ...
        self.conn.send(message, target_ip)
        ...
        recv_data = self.conn.receive()
        if recv_data is not None:
            ...
        ...
    # Destructing.
    def __del__(self):
        ...
        del(self.conn)
        ...